sudo: required

services:
  - docker

branches:
  only:
    - master
    - travis

before_script:
  # this install.sh script requires sudo
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  # From https://github.com/travis-ci/travis-ci/issues/4704 to fix an issue 
  # where Travis errors out if too much information goes on stdout and some
  # npm package is blocking stdout.
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'

  - ./start_env.sh deploy_pipeline
