# Development environment for
#   - Python Linting
#   - Python Testing
#   - Flask debugging

FROM python:3.7.3-slim

# ## General ##
WORKDIR /opt/app

# Install Python packages
ADD requirements.txt .
RUN pip install --no-cache-dir -q -r requirements.txt

# Environment variable for flask
ENV FLASK_APP app/my_app.py
ENV FLASK_DEBUG 1

# Use this is you want to load straight into flask
# CMD ["flask", "run", "--host=0.0.0.0"]

ENTRYPOINT ["bash"]
